name: My Titanic Project Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test basic imports
      run: |
        python -c "
        import pandas as pd
        import numpy as np
        import sklearn
        print('✅ All packages imported successfully')
        "
    
    - name: Test data file exists
      run: |
        python -c "
        import os
        assert os.path.exists('data/raw/titanic.csv'), 'Dataset file should exist'
        print('✅ Dataset file found')
        "
    
    - name: Test basic data loading
      run: |
        python -c "
        import pandas as pd
        df = pd.read_csv('data/raw/titanic.csv')
        print(f'✅ Dataset loaded successfully: {df.shape}')
        assert df.shape[0] > 0, 'Dataset should not be empty'
        print('✅ Data validation passed')
        "
    
    - name: Test project structure
      run: |
        python -c "
        import os
        dirs = ['src', 'data', 'notebooks', 'reports']
        for d in dirs:
            assert os.path.exists(d), f'{d} directory should exist'
        print('✅ Project structure validated')
        "
        import os
        
        # Check required directories
        assert os.path.exists('data/raw'), 'data/raw directory missing'
        assert os.path.exists('src'), 'src directory missing'
        assert os.path.exists('notebooks'), 'notebooks directory missing'
        
        # Check required files
        assert os.path.exists('README.md'), 'README.md missing'
        assert os.path.exists('requirements.txt'), 'requirements.txt missing'
        assert os.path.exists('data/raw/titanic.csv'), 'Titanic dataset missing'
        
        print('✅ Project structure validation passed')
        "
